import { MagazineLineDto } from "@/api/dto/magazine/magazine-line.dto";

export const userLineDefault = {
  id: "abc",
      name: "sheep",
      imageUrl: null,
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
}

export const regionDefault = {
  id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
}

export const simpleMagazineLineDto = [
  {
    id: "abcd",
    title: "제주도 여행을 다녀왔는데요!! 아주 어메이징 했어요.",
    rank: 1,
    writer: {
      id: "abc",
      name: "sheep",
      imageUrl: null,
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
    },
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
  },
  {
    id: "abcd",
    title: "제주도 여행을 다녀왔는데요!! 아주 어메이징 했어요.",
    rank: 2,
    writer: {
      id: "abc",
      name: "sheep",
      imageUrl: null,
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
    },
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
  },
  {
    id: "abcd",
    title: "제주도 여행을 다녀왔는데요!! 아주 어메이징 했어요.",
    rank: 3,
    writer: {
      id: "abc",
      name: "sheep",
      imageUrl: null,
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
    },
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
  },
  {
    id: "abcd",
    title: "제주도 여행을 다녀왔는데요!! 아주 어메이징 했어요.",
    rank: 4,
    writer: {
      id: "abc",
      name: "sheep",
      imageUrl: null,
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
    },
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
  },
  {
    id: "abcd",
    title: "제주도 여행을 다녀왔는데요!! 아주 어메이징 했어요.",
    rank: 5,
    writer: {
      id: "abc",
      name: "sheep",
      imageUrl: null,
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
    },
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
  },
];

export const awardedUserLineDto = [
  {
    id: 'strd',
    name: 'sheep1',
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
    imageUrl: null,
    rank: 1
  },
    {
    id: 'strd',
    name: 'sheep2',
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
    imageUrl: null,
    rank: 2
  },
    {
    id: 'strd',
    name: 'sheep3',
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
    imageUrl: null,
    rank: 3
  },
    {
    id: 'strd',
    name: 'sheep4',
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
    imageUrl: null,
    rank: 4
  },
    {
    id: 'strd',
    name: 'sheep5',
    region: {
      id: "default",
      name_ch: "全部",
      name_fr: "Totalité",
      name_ge: "Gesamt",
      name_en: "All",
      name_hk: "全部",
      name_it: "Intero",
      name_jp: "全体",
      name_kr: "전체",
      name_vi: "Toàn bộ",
      flag: "🌏",
    },
    imageUrl: null,
    rank: 5
  }
];

export const magazineLineDto: MagazineLineDto[] = [
  {
    id: 'abc',
    title: "제주도 여행을 떠나요!! 진짜로 제발로 완전 그냥 떠나요!",
    imageUrl: null,
    writer: {
      id: 'strd',
      name: 'sheep5',
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
      imageUrl: null,
    },
    createdAt: '2012.10.9',
    likeCount: 10,
    photoLikeCount: 10,
    writingLikeCount: 10,
    replyCount: 10
  },
  {
    id: 'abc',
    title: "제주도 여행을 떠나요!! 진짜로 제발로 완전 그냥 떠나요!",
    imageUrl: null,
    writer: {
      id: 'strd',
      name: 'sheep5',
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
      imageUrl: null,
    },
    createdAt: '2012.10.9',
    likeCount: 10,
    photoLikeCount: 10,
    writingLikeCount: 10,
    replyCount: 10
  },
  {
    id: 'abc',
    title: "제주도 여행을 떠나요!! 진짜로 제발로 완전 그냥 떠나요!",
    imageUrl: null,
    writer: {
      id: 'strd',
      name: 'sheep5',
      region: {
        id: "default",
        name_ch: "全部",
        name_fr: "Totalité",
        name_ge: "Gesamt",
        name_en: "All",
        name_hk: "全部",
        name_it: "Intero",
        name_jp: "全体",
        name_kr: "전체",
        name_vi: "Toàn bộ",
        flag: "🌏",
      },
      imageUrl: null,
    },
    createdAt: '2012.10.9',
    likeCount: 10,
    photoLikeCount: 10,
    writingLikeCount: 10,
    replyCount: 10
  }
]
